name: Deploy nodejs

on: # do actions on
  push: # when i push the code
    branches: # on branches
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest # run on github's ubuntu server

    steps:
    - name: Checkout Code
      uses: actions.checkout@v4

    - name: Deploy via ssh
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{secrets.SSH_HOST}}
        username: ubuntu
        key: ${{secrets.SSH_KEY}}
        script: |
          cd /home/ubuntu/nodejs-ci-cd
          git pull
          docker compose up -d --build